project:
  type: website

website:
  title: NSF Grant Terminations
  navbar:
    right:
      - icon: github
        href: https://github.com/INFO-526-SU25/final-project-nathanielcross04
    left:
      - text: Project
        href: index.qmd
      - text: Proposal
        href: proposal.qmd
      - text: Presentation
        href: presentation.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true


execute:
  freeze: auto
